import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";
import { AuthProvider } from "../context/AuthContext";
import { ThemeProvider } from "next-themes";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "To-Do List App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ` } suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-white text-black dark:bg-gray-950  dark:text-white transition-all duration-300">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <AuthProvider>
        <NavBar/>
        {children}
        </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
